import type { PluginManifest } from "@/types/plugin";
import { usePluginStore } from "@/store/plugin-store";

export function useRegisterPlugins() {
  const registerPlugins = usePluginStore((s) => s.registerPlugins);

  const manifests: PluginManifest[] = [
    {
      id: "fullcalendar",
      name: "FullCalendar",
      description: "Interactive calendar with month, week, and day views for scheduling and due dates.",
      version: "6.1.15",
      author: "FullCalendar LLC",
      icon: "CalendarDays",
      category: "calendar",
      homepage: "https://fullcalendar.io",
      npmPackage: "@fullcalendar/core",
      isBuiltIn: false,
    },
    {
      id: "dropzone",
      name: "Dropzone",
      description: "Drag-and-drop file uploads with preview, progress tracking, and multi-file support.",
      version: "6.0.0",
      author: "React Dropzone",
      icon: "Upload",
      category: "file",
      homepage: "https://react-dropzone.js.org",
      npmPackage: "react-dropzone",
      isBuiltIn: false,
    },
    {
      id: "quill-editor",
      name: "Quill Editor",
      description: "Rich text WYSIWYG editor for invoice notes, email templates, and descriptions.",
      version: "2.0.0",
      author: "Quill",
      icon: "FileText",
      category: "editor",
      homepage: "https://quilljs.com",
      npmPackage: "react-quill-new",
      isBuiltIn: false,
    },
    {
      id: "flatpickr",
      name: "Flatpickr",
      description: "Lightweight date and time picker with range selection, localization, and custom formats.",
      version: "4.6.13",
      author: "Flatpickr",
      icon: "Calendar",
      category: "ui",
      homepage: "https://flatpickr.js.org",
      npmPackage: "flatpickr",
      isBuiltIn: false,
    },
    {
      id: "sortable",
      name: "SortableJS",
      description: "Drag-and-drop sorting for invoice line items, Kanban cards, and list reordering.",
      version: "9.0.0",
      author: "dnd-kit",
      icon: "GripVertical",
      category: "ui",
      homepage: "https://dndkit.com",
      npmPackage: "@dnd-kit/sortable",
      isBuiltIn: false,
    },
    {
      id: "pdf-viewer",
      name: "PDF Viewer",
      description: "Inline PDF preview for invoices, receipts, and attached documents.",
      version: "9.2.0",
      author: "react-pdf",
      icon: "File",
      category: "file",
      homepage: "https://react-pdf.org",
      npmPackage: "react-pdf",
      isBuiltIn: false,
    },
    {
      id: "apexcharts",
      name: "ApexCharts",
      description: "Interactive charts with rich customization — area, bar, line, donut, and more.",
      version: "4.1.0",
      author: "ApexCharts",
      icon: "BarChart3",
      category: "chart",
      homepage: "https://apexcharts.com",
      npmPackage: "apexcharts",
      isBuiltIn: false,
    },
    {
      id: "chartjs",
      name: "Chart.js",
      description: "Simple yet flexible charting library with line, bar, radar, doughnut char ts.",
      version: "4.4.7",
      author: "Chart.js",
      icon: "ChartPie",
      category: "chart",
      homepage: "https://www.chartjs.org",
      npmPackage: "chart.js",
      isBuiltIn: false,
    },
    {
      id: "tom-select",
      name: "Tom Select",
      description: "Enhanced select inputs with tagging, searching, multi-select, and remote data loading.",
      version: "2.4.1",
      author: "Tom Select",
      icon: "ListChecks",
      category: "ui",
      homepage: "https://tom-select.js.org",
      npmPackage: "tom-select",
      isBuiltIn: false,
    },
    {
      id: "datatables",
      name: "DataTables",
      description: "Feature-rich table plugin with advanced search, column visibility, and server-side processing.",
      version: "2.2.2",
      author: "DataTables",
      icon: "Table",
      category: "table",
      homepage: "https://datatables.net",
      npmPackage: "datatables.net",
      isBuiltIn: false,
    },
  ];

  return { registerPlugins, manifests };
}
